name: Build Android APK

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Android SDK and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          python3-pip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          cmake \
          libffi-dev \
          libssl-dev

    - name: Install Buildozer and Cython
      run: |
        pip install cython buildozer

    - name: Build APK (single arch for faster build)
      run: |
        buildozer android debug --arch arm64-v8a

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: sudoku-apk
        path: bin/*.apk
        retention-days: 30
